### PR TITLE
Added form css layout

### PR DESCRIPTION
**Pull request by creadicted**
Added css to forms

grafik

### CODE REVIEW

**Comment by oetherington** [comment]
Nice work - that looks a lot nicer!

Maybe we could create a separate TextInput component that just returns this:
```
<label className="block text-gray-700 text-sm font-bold mb-5" htmlFor="firstName">
  <p>{t("First Name")}</p>
  <input
    className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
    name="firstName"
    id="firstName" type="text"/>
</label>
```
and takes `htmlFor`, `text` and `name` as props. Then, if we want to make any changes in the future, we only need to update it in one place.

We could also add another component for the form headings for the same reason.

**Comment by creadicted** [comment]
I do not know my way around react. 
We could also use a react forms library for easier validation.

**Comment by oetherington** [comment]
Ah, ok, that's fine. I'll merge this then and I'll make the change. Thanks!

**Comment by MnsrIl** [comment]
@oetherington I can take this (TextInput component), if you don't mind

**Comment by oetherington** [comment]
@MnsrIl Sure - go for it!

**Pull request merged**
