### PR TITLE
There was a typo in "across Ukraine"

### PR DESCRIPTION
**Pull request by creadicted**

### CODE REVIEW

**Comment by oetherington** [comment]
Well spotted!

**Comment by oetherington** [comment]
FYI, @shenanigansd - We also need to update the github readme again

**Comment by shenanigansd** [comment]
> FYI, @shenanigansd - We also need to update the github readme again

What needs to be updated?

**Comment by oetherington** [comment]
@shenanigansd Ignore me - I'm an idiot. I thought the typo was in some text from the readme, but it's actually from a totally unrelated string. Sorry!

**Pull request merged**
