### PR TITLE
Code refactoring

### PR DESCRIPTION
**Pull request by MnsrIl**
What I've done:

- Rename Components folder to component
- Rename globalState folder to store folder
- Refactor component's imports to default imports
- Made constants file more useful

### CODE REVIEW

**Comment by oetherington** [comment]
Nice work! These are really good changes.

I've also got the api-integration-v1 branch that I've got to merge which will have some conflicts with this. I'm going to merge the other branch first because I think it will be a lot easier to fix the conflicts in this branch than in that branch. It should also make this branch a bit simpler as it removes the redux store completely, as well as some redundant components.

Let me know if you want any help with the conflicts. Thanks!

**Comment by MnsrIl** [comment]
Okay, I'll solve this!

**Comment by MnsrIl** [comment]
@oetherington Probably, I done with this. Please, check it and let me know, didn't I miss anything?

**Comment by oetherington** [comment]
Looks good to me! Thanks!

**Pull request merged**
